name: CI 🕵
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install ruff
        run: pipx install ruff
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry" # see https://github.com/actions/setup-python#caching-packages-dependencies
      - run: poetry install
      - run: poetry run make spin
